### PR TITLE
OpenEMS build script : select arbitrary upstream version

### PR DESCRIPTION
**Pull request by thomaslepoix**
I added possibility to produce a `.deb` package from upstream Github versions, let me know if it's ok for you.

### CODE REVIEW

**Comment by 0xCoto** [comment]
@thomaslepoix Thank you for the script - tried it on a fresh Ubuntu VM:
```bash
chmod +x build_solver.sh
./build_solver.sh --setup
```
And then when I try `./build_solver.sh`, I get an error `E: Unable to locate package openems-build-deps`:

Full output:
```sh
Reading package lists... Done
NOTICE: 'openems' packaging is maintained in the 'Git' version control system at:
https://salsa.debian.org/science-team/openems.git
Please use:
git clone https://salsa.debian.org/science-team/openems.git
to retrieve the latest (possibly unreleased) updates to the package.
Need to get 2999 kB of source archives.
Get:1 http://gr.archive.ubuntu.com/ubuntu focal/universe openems 0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3 (dsc) [2866 B]
Get:2 http://gr.archive.ubuntu.com/ubuntu focal/universe openems 0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3 (tar) [2982 kB]
Get:3 http://gr.archive.ubuntu.com/ubuntu focal/universe openems 0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3 (diff) [14,5 kB]
Fetched 2999 kB in 4s (673 kB/s)
Download complete and in download only mode
Cloning into 'openEMS-Project'...
remote: Enumerating objects: 361, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 361 (delta 16), reused 25 (delta 10), pack-reused 329
Receiving objects: 100% (361/361), 74.69 KiB | 910.00 KiB/s, done.
Resolving deltas: 100% (183/183), done.
Submodule 'AppCSXCAD' (https://github.com/thliebig/AppCSXCAD.git) registered for path 'AppCSXCAD'
Submodule 'CSXCAD' (https://github.com/thliebig/CSXCAD.git) registered for path 'CSXCAD'
Submodule 'CTB' (https://github.com/thliebig/CTB.git) registered for path 'CTB'
Submodule 'QCSXCAD' (https://github.com/thliebig/QCSXCAD.git) registered for path 'QCSXCAD'
Submodule 'fparser' (https://github.com/thliebig/fparser.git) registered for path 'fparser'
Submodule 'hyp2mat' (https://github.com/koendv/hyp2mat.git) registered for path 'hyp2mat'
Submodule 'openEMS' (https://github.com/thliebig/openEMS.git) registered for path 'openEMS'
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/AppCSXCAD'...
remote: Enumerating objects: 253, done.        
remote: Counting objects: 100% (6/6), done.        
remote: Compressing objects: 100% (4/4), done.        
remote: Total 253 (delta 2), reused 6 (delta 2), pack-reused 247        
Receiving objects: 100% (253/253), 50.70 KiB | 674.00 KiB/s, done.
Resolving deltas: 100% (150/150), done.
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/CSXCAD'...
remote: Enumerating objects: 3007, done.        
remote: Counting objects: 100% (37/37), done.        
remote: Compressing objects: 100% (23/23), done.        
remote: Total 3007 (delta 18), reused 29 (delta 14), pack-reused 2970        
Receiving objects: 100% (3007/3007), 982.57 KiB | 2.35 MiB/s, done.
Resolving deltas: 100% (1922/1922), done.
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/CTB'...
remote: Enumerating objects: 47, done.        
remote: Total 47 (delta 0), reused 0 (delta 0), pack-reused 47        
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/QCSXCAD'...
remote: Enumerating objects: 809, done.        
remote: Counting objects: 100% (18/18), done.        
remote: Compressing objects: 100% (12/12), done.        
remote: Total 809 (delta 7), reused 10 (delta 6), pack-reused 791        
Receiving objects: 100% (809/809), 797.97 KiB | 1.82 MiB/s, done.
Resolving deltas: 100% (529/529), done.
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/fparser'...
remote: Enumerating objects: 89, done.        
remote: Total 89 (delta 0), reused 0 (delta 0), pack-reused 89        
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/hyp2mat'...
remote: Enumerating objects: 1780, done.        
remote: Counting objects: 100% (3/3), done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 1780 (delta 0), reused 1 (delta 0), pack-reused 1777        
Receiving objects: 100% (1780/1780), 3.55 MiB | 3.66 MiB/s, done.
Resolving deltas: 100% (1134/1134), done.
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/openEMS'...
remote: Enumerating objects: 7346, done.        
remote: Counting objects: 100% (137/137), done.        
remote: Compressing objects: 100% (88/88), done.        
remote: Total 7346 (delta 62), reused 108 (delta 49), pack-reused 7209        
Receiving objects: 100% (7346/7346), 4.61 MiB | 4.14 MiB/s, done.
Resolving deltas: 100% (4250/4250), done.
Submodule path 'AppCSXCAD': checked out '97ba30e4ad9ed03209018a383c6a0d703470698e'
Submodule path 'CSXCAD': checked out '3c4fb665d934349e048fbcc31d6be203483b5e98'
Submodule path 'CTB': checked out '5ac29367ebb7e30e78dd3db13a21464756855599'
Submodule path 'QCSXCAD': checked out '3f09a8b83be6c945964ec3f29f8724ace563897e'
Submodule path 'fparser': checked out 'a59e1f51e32096bfe2a0a2640d5dffc7ae6ba37b'
Submodule path 'hyp2mat': checked out 'b15f749849610066e6c09da5b5e3f97e3317ba8a'
Submodule path 'openEMS': checked out 'd4448fa294723be9bfe270db8ff751faf97c8b85'
debian/
debian/CSXCAD.packinfo/
debian/CSXCAD.packinfo/DESCRIPTION
debian/CSXCAD.packinfo/INDEX
debian/CSXCAD.packinfo/NEWS
debian/FIXME
debian/README.source
debian/changelog
debian/control
debian/copyright
debian/gbp.conf
debian/gitlab-ci.yml
debian/libcsxcad0.install
debian/libcsxcad0.shlibs
debian/libnf2ff0.install
debian/libnf2ff0.shlibs
debian/libopenems-dev.install
debian/libopenems0.install
debian/libopenems0.shlibs
debian/libqcsxcad0.install
debian/libqcsxcad0.shlibs
debian/man/
debian/man/AppCSXCAD.txt
debian/man/genmanpages.sh
debian/man/nf2ff.txt
debian/man/openEMS.txt
debian/octave-openems.install
debian/openEMS.packinfo/
debian/openEMS.packinfo/DESCRIPTION
debian/openEMS.packinfo/INDEX
debian/openEMS.packinfo/NEWS
debian/openems.install
debian/openems.manpages
debian/patches/
debian/patches/0001-Fix-path-to-binaries-for-Debian.patch
debian/patches/0002-Spelling-fixes.patch
debian/patches/0003-More-things-to-fix-build.patch
debian/patches/0004-link-more.patch
debian/patches/0005-Deletede-CVS-dir-lintian.patch
debian/patches/0006-Don-t-exit-from-library.patch
debian/patches/0007-Fix-some-imports-to-make-python-interface-work.patch
debian/patches/series
debian/python3-openems.install
debian/rules
debian/source/
debian/source/format
debian/tests/
debian/tests/control
debian/tests/octave-load
debian/tests/python3-import
debian/watch
 dpkg-buildpackage -us -uc -ui -b
dpkg-buildpackage: info: source package openems
dpkg-buildpackage: info: source version 0.0.35+git20220220.6508214-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Thomas Lepoix <thomas.lepoix@protonmail.ch>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 12) cmake libhdf5-dev libboost-all-dev libcgal-dev libcgal-qt5-dev libtinyxml-dev libvtk7-qt-dev libfparser-dev dh-octave | octave-pkg-dev cython3 chrpath dh-python python3-all-dev txt2man
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package openems-build-deps
Reading package lists... Done
E: Unsupported file ./libcsxcad0_*.deb given on commandline
E: Unsupported file ./libnf2ff0_*.deb given on commandline
E: Unsupported file ./libopenems0_*.deb given on commandline
E: Unsupported file ./libqcsxcad0_*.deb given on commandline
E: Unsupported file ./openems_*.deb given on commandline
E: Unsupported file ./octave-openems_*.deb given on commandline
E: Unsupported file ./python3-openems_*.deb given on commandline
```

Any ideas?

**Comment by thomaslepoix** [comment]
Better?

**Comment by 0xCoto** [comment]
Nope, unfortunately it still seems to fail:
```sh
Reading package lists... Done
NOTICE: 'openems' packaging is maintained in the 'Git' version control system at:
https://salsa.debian.org/science-team/openems.git
Please use:
git clone https://salsa.debian.org/science-team/openems.git
to retrieve the latest (possibly unreleased) updates to the package.
Need to get 2999 kB of source archives.
Get:1 http://gr.archive.ubuntu.com/ubuntu focal/universe openems 0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3 (dsc) [2866 B]
Get:2 http://gr.archive.ubuntu.com/ubuntu focal/universe openems 0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3 (tar) [2982 kB]
Get:3 http://gr.archive.ubuntu.com/ubuntu focal/universe openems 0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3 (diff) [14,5 kB]
Fetched 2999 kB in 1s (2209 kB/s)
Download complete and in download only mode
Cloning into 'openEMS-Project'...
remote: Enumerating objects: 361, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 361 (delta 16), reused 25 (delta 10), pack-reused 329
Receiving objects: 100% (361/361), 74.69 KiB | 849.00 KiB/s, done.
Resolving deltas: 100% (183/183), done.
Submodule 'AppCSXCAD' (https://github.com/thliebig/AppCSXCAD.git) registered for path 'AppCSXCAD'
Submodule 'CSXCAD' (https://github.com/thliebig/CSXCAD.git) registered for path 'CSXCAD'
Submodule 'CTB' (https://github.com/thliebig/CTB.git) registered for path 'CTB'
Submodule 'QCSXCAD' (https://github.com/thliebig/QCSXCAD.git) registered for path 'QCSXCAD'
Submodule 'fparser' (https://github.com/thliebig/fparser.git) registered for path 'fparser'
Submodule 'hyp2mat' (https://github.com/koendv/hyp2mat.git) registered for path 'hyp2mat'
Submodule 'openEMS' (https://github.com/thliebig/openEMS.git) registered for path 'openEMS'
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/AppCSXCAD'...
remote: Enumerating objects: 253, done.        
remote: Counting objects: 100% (6/6), done.        
remote: Compressing objects: 100% (4/4), done.        
remote: Total 253 (delta 2), reused 6 (delta 2), pack-reused 247        
Receiving objects: 100% (253/253), 50.70 KiB | 432.00 KiB/s, done.
Resolving deltas: 100% (150/150), done.
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/CSXCAD'...
remote: Enumerating objects: 3007, done.        
remote: Counting objects: 100% (37/37), done.        
remote: Compressing objects: 100% (23/23), done.        
remote: Total 3007 (delta 18), reused 29 (delta 14), pack-reused 2970        
Receiving objects: 100% (3007/3007), 982.57 KiB | 1.25 MiB/s, done.
Resolving deltas: 100% (1922/1922), done.
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/CTB'...
remote: Enumerating objects: 47, done.        
remote: Total 47 (delta 0), reused 0 (delta 0), pack-reused 47        
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/QCSXCAD'...
remote: Enumerating objects: 809, done.        
remote: Counting objects: 100% (18/18), done.        
remote: Compressing objects: 100% (12/12), done.        
remote: Total 809 (delta 7), reused 10 (delta 6), pack-reused 791        
Receiving objects: 100% (809/809), 797.97 KiB | 2.08 MiB/s, done.
Resolving deltas: 100% (529/529), done.
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/fparser'...
remote: Enumerating objects: 89, done.        
remote: Total 89 (delta 0), reused 0 (delta 0), pack-reused 89
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/hyp2mat'...
remote: Enumerating objects: 1780, done.        
remote: Counting objects: 100% (3/3), done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 1780 (delta 0), reused 1 (delta 0), pack-reused 1777        
Receiving objects: 100% (1780/1780), 3.55 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (1134/1134), done.
Cloning into '/home/abc/compute-servers/build_debian/openEMS-Project/openEMS'...
remote: Enumerating objects: 7346, done.        
remote: Counting objects: 100% (51/51), done.        
remote: Compressing objects: 100% (39/39), done.        
remote: Total 7346 (delta 21), reused 26 (delta 12), pack-reused 7295        
Receiving objects: 100% (7346/7346), 4.56 MiB | 3.91 MiB/s, done.
Resolving deltas: 100% (4288/4288), done.
Submodule path 'AppCSXCAD': checked out '97ba30e4ad9ed03209018a383c6a0d703470698e'
Submodule path 'CSXCAD': checked out '3c4fb665d934349e048fbcc31d6be203483b5e98'
Submodule path 'CTB': checked out '5ac29367ebb7e30e78dd3db13a21464756855599'
Submodule path 'QCSXCAD': checked out '3f09a8b83be6c945964ec3f29f8724ace563897e'
Submodule path 'fparser': checked out 'a59e1f51e32096bfe2a0a2640d5dffc7ae6ba37b'
Submodule path 'hyp2mat': checked out 'b15f749849610066e6c09da5b5e3f97e3317ba8a'
Submodule path 'openEMS': checked out 'd4448fa294723be9bfe270db8ff751faf97c8b85'
debian/
debian/CSXCAD.packinfo/
debian/CSXCAD.packinfo/DESCRIPTION
debian/CSXCAD.packinfo/INDEX
debian/CSXCAD.packinfo/NEWS
debian/FIXME
debian/README.source
debian/changelog
debian/control
debian/copyright
debian/gbp.conf
debian/gitlab-ci.yml
debian/libcsxcad0.install
debian/libcsxcad0.shlibs
debian/libnf2ff0.install
debian/libnf2ff0.shlibs
debian/libopenems-dev.install
debian/libopenems0.install
debian/libopenems0.shlibs
debian/libqcsxcad0.install
debian/libqcsxcad0.shlibs
debian/man/
debian/man/AppCSXCAD.txt
debian/man/genmanpages.sh
debian/man/nf2ff.txt
debian/man/openEMS.txt
debian/octave-openems.install
debian/openEMS.packinfo/
debian/openEMS.packinfo/DESCRIPTION
debian/openEMS.packinfo/INDEX
debian/openEMS.packinfo/NEWS
debian/openems.install
debian/openems.manpages
debian/patches/
debian/patches/0001-Fix-path-to-binaries-for-Debian.patch
debian/patches/0002-Spelling-fixes.patch
debian/patches/0003-More-things-to-fix-build.patch
debian/patches/0004-link-more.patch
debian/patches/0005-Deletede-CVS-dir-lintian.patch
debian/patches/0006-Don-t-exit-from-library.patch
debian/patches/0007-Fix-some-imports-to-make-python-interface-work.patch
debian/patches/series
debian/python3-openems.install
debian/rules
debian/source/
debian/source/format
debian/tests/
debian/tests/control
debian/tests/octave-load
debian/tests/python3-import
debian/watch
mk-build-deps: You must have equivs installed to use this program.
 dpkg-buildpackage -us -uc -ui -b
dpkg-buildpackage: info: source package openems
dpkg-buildpackage: info: source version 0.0.35+git20220220.6508214-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Thomas Lepoix <thomas.lepoix@protonmail.ch>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 12) cmake libhdf5-dev libboost-all-dev libcgal-dev libcgal-qt5-dev libtinyxml-dev libvtk7-qt-dev libfparser-dev dh-octave | octave-pkg-dev cython3 chrpath dh-python python3-all-dev txt2man
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package openems-build-deps
Reading package lists... Done
E: Unsupported file ./libcsxcad0_*.deb given on commandline
E: Unsupported file ./libnf2ff0_*.deb given on commandline
E: Unsupported file ./libopenems0_*.deb given on commandline
E: Unsupported file ./libqcsxcad0_*.deb given on commandline
E: Unsupported file ./openems_*.deb given on commandline
E: Unsupported file ./octave-openems_*.deb given on commandline
E: Unsupported file ./python3-openems_*.deb given on commandline
```

**Comment by 0xCoto** [comment]
**Update:** Appended `sudo apt install -y equivs` right after `sudo apt install -y devscripts` to tackle the main issue:
```sh
mk-build-deps: You must have equivs installed to use this program.
```
Seems to continue well. Let's see...

**Comment by 0xCoto** [comment]
@thomaslepoix Yeah, the install seems to have worked OK, but unfortunately `pyems` is still not working properly (not recognizing the horn in the [`horn_antenna.py`](https://github.com/matthuszagh/pyems/blob/master/examples/horn_antenna.py) example):

```py
$ python3 horn_antenna.py 
/home/abc/.local/lib/python3.8/site-packages/pyems/mesh.py:664: UserWarning: Mesh line at pos 209.9044 for dimension 2 violates smoothness. Smoothness was set to 1.50 but this line creates a spacing with factor 1.98. For convenience the last three lines are: 202.3610, 204.8937 and 209.9044.
  warn(
CSPrimPolyhedronReader::ReadFromXML: Error, can't read filename!
Continue simulation (y/n)? 


```

image

**Comment by thomaslepoix** [comment]
Hm strange..
- Is there any older installation on your system that could take precedence over the new `.deb`?
- Did you try a manual installation from upstream repo? is it better?

**Comment by 0xCoto** [comment]
- Nope, fresh installation on a just-setup VM.
- Any particular way I should go about this? Should I change the repository in the script to something else, or?

**Comment by thomaslepoix** [comment]
Ok, I found why it persists https://github.com/thliebig/CSXCAD/pull/26

**Comment by thomaslepoix** [comment]
If you don't want to wait for Thorsten to merge my patch, I've just added an option to chose git repository URL, so you can fork [thliebig/openEMS-Project](https://github.com/thliebig/openEMS-Project) and change git submodules to depends on my fork of [thomaslepoix/CSXCAD](https://github.com/thomaslepoix/CSXCAD) instead.

**Comment by 0xCoto** [comment]
@thomaslepoix FYI after Thorsten's commits, I retried running the script as usual (i.e. after a fresh VM) using
```sh
./build_solver.sh --setup
./build_solver.sh
```
and the issue still persists, so apparently his changes didn't fix the issue.

**Comment by 0xCoto** [comment]
Also added some additional commands to prepare the script for fresh Ubuntu installations (`git`, `pip`, `setuptools`): https://github.com/BlitPlatform/compute-servers/commit/e2a75d6948ba8aee4d22c8061eb5e711e2a7c210

**Comment by 0xCoto** [comment]
@jmwilson I believe the new git structure is incompatible with the [build script](https://github.com/BlitPlatform/compute-servers/blob/main/build_solver.sh). Tried to build it using a Dockerfile (although the same happens on a regular machine with Ubuntu 20.04). Any ideas? (looping @thomaslepoix in case there's any obvious issues)
```dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq
RUN apt-get -y --no-install-recommends install wget
RUN mkdir gpu_task
RUN cd gpu_task
RUN wget https://raw.githubusercontent.com/BlitPlatform/compute-servers/main/build_solver.sh --no-check-certificate
RUN chmod +x build_solver.sh
RUN ./build_solver.sh --setup
RUN ./build_solver.sh
RUN ./build_solver.sh --benchmark
```
`docker build --no-cache -t my_image .`
```py
[+] Building 317.8s (12/13)
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 446B                                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                               1.7s
 => CACHED [ 1/10] FROM docker.io/library/ubuntu:20.04@sha256:af5efa9c28de78b754777af9b4d850112cad01899a5d37d2617bb94dc63a49aa                                                                                0.0s
 => [ 2/10] RUN apt-get update -qq                                                                                                                                                                           51.8s
 => [ 3/10] RUN apt-get -y --no-install-recommends install wget                                                                                                                                               7.5s
 => [ 4/10] RUN mkdir gpu_task                                                                                                                                                                                0.5s
 => [ 5/10] RUN cd gpu_task                                                                                                                                                                                   0.6s
 => [ 6/10] RUN wget https://raw.githubusercontent.com/BlitPlatform/compute-servers/main/build_solver.sh --no-check-certificate                                                                               1.1s
 => [ 7/10] RUN chmod +x build_solver.sh                                                                                                                                                                      0.7s
 => [ 8/10] RUN ./build_solver.sh --setup                                                                                                                                                                   230.4s
 => ERROR [ 9/10] RUN ./build_solver.sh                                                                                                                                                                      23.4s
------
 > [ 9/10] RUN ./build_solver.sh:
#11 0.581 Reading package lists...
#11 2.064 NOTICE: 'openems' packaging is maintained in the 'Git' version control system at:
#11 2.064 https://salsa.debian.org/science-team/openems.git
#11 2.064 Please use:
#11 2.064 git clone https://salsa.debian.org/science-team/openems.git
#11 2.064 to retrieve the latest (possibly unreleased) updates to the package.
#11 2.064 Need to get 2999 kB of source archives.
#11 2.064 Get:1 http://archive.ubuntu.com/ubuntu focal/universe openems 0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3 (dsc) [2866 B]
#11 2.228 Get:2 http://archive.ubuntu.com/ubuntu focal/universe openems 0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3 (tar) [2982 kB]
#11 10.59 Get:3 http://archive.ubuntu.com/ubuntu focal/universe openems 0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3 (diff) [14.5 kB]
#11 10.62 Fetched 2999 kB in 9s (327 kB/s)
#11 10.62 Download complete and in download only mode
#11 10.62 W: Download is performed unsandboxed as root as file 'openems_0.0.35+git20190103.6a75e98+dfsg.1-2ubuntu3.dsc' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
#11 10.62 Cloning into 'openEMS-Project'...
#11 11.48 Submodule 'AppCSXCAD' (https://github.com/thliebig/AppCSXCAD.git) registered for path 'AppCSXCAD'
#11 11.48 Submodule 'CSXCAD' (https://github.com/thliebig/CSXCAD.git) registered for path 'CSXCAD'
#11 11.48 Submodule 'CTB' (https://github.com/thliebig/CTB.git) registered for path 'CTB'
#11 11.48 Submodule 'QCSXCAD' (https://github.com/thliebig/QCSXCAD.git) registered for path 'QCSXCAD'
#11 11.48 Submodule 'fparser' (https://github.com/thliebig/fparser.git) registered for path 'fparser'
#11 11.48 Submodule 'hyp2mat' (https://github.com/koendv/hyp2mat.git) registered for path 'hyp2mat'
#11 11.48 Submodule 'openEMS' (https://github.com/BlitPlatform/openems.git) registered for path 'openEMS'
#11 11.49 Cloning into '/build_debian/openEMS-Project/AppCSXCAD'...
#11 12.40 Cloning into '/build_debian/openEMS-Project/CSXCAD'...
#11 13.57 Cloning into '/build_debian/openEMS-Project/CTB'...
#11 14.19 Cloning into '/build_debian/openEMS-Project/QCSXCAD'...
#11 15.22 Cloning into '/build_debian/openEMS-Project/fparser'...
#11 16.09 Cloning into '/build_debian/openEMS-Project/hyp2mat'...
#11 17.83 Cloning into '/build_debian/openEMS-Project/openEMS'...
#11 20.05 Submodule path 'AppCSXCAD': checked out '97ba30e4ad9ed03209018a383c6a0d703470698e'
#11 20.09 Submodule path 'CSXCAD': checked out 'cd9decb4d9cebe3c8bf115e2c0ee73f730f22da1'
#11 20.11 Submodule path 'CTB': checked out '5ac29367ebb7e30e78dd3db13a21464756855599'
#11 20.14 Submodule path 'QCSXCAD': checked out '3f09a8b83be6c945964ec3f29f8724ace563897e'
#11 20.17 Submodule path 'fparser': checked out 'a59e1f51e32096bfe2a0a2640d5dffc7ae6ba37b'
#11 20.20 Submodule path 'hyp2mat': checked out 'b15f749849610066e6c09da5b5e3f97e3317ba8a'
#11 20.27 Submodule path 'openEMS': checked out '8816d3f24f5dc053f113315e63794507973c492b'
#11 20.28 fatal: No names found, cannot describe anything.
#11 20.29 debian/
#11 20.29 debian/CSXCAD.packinfo/
#11 20.29 debian/CSXCAD.packinfo/DESCRIPTION
#11 20.29 debian/CSXCAD.packinfo/INDEX
#11 20.29 debian/CSXCAD.packinfo/NEWS
#11 20.29 debian/FIXME
#11 20.29 debian/README.source
#11 20.29 debian/changelog
#11 20.29 debian/control
#11 20.29 debian/copyright
#11 20.29 debian/gbp.conf
#11 20.29 debian/gitlab-ci.yml
#11 20.29 debian/libcsxcad0.install
#11 20.29 debian/libcsxcad0.shlibs
#11 20.29 debian/libnf2ff0.install
#11 20.29 debian/libnf2ff0.shlibs
#11 20.29 debian/libopenems-dev.install
#11 20.29 debian/libopenems0.install
#11 20.29 debian/libopenems0.shlibs
#11 20.29 debian/libqcsxcad0.install
#11 20.29 debian/libqcsxcad0.shlibs
#11 20.29 debian/man/
#11 20.29 debian/man/AppCSXCAD.txt
#11 20.29 debian/man/genmanpages.sh
#11 20.29 debian/man/nf2ff.txt
#11 20.29 debian/man/openEMS.txt
#11 20.29 debian/octave-openems.install
#11 20.29 debian/openEMS.packinfo/
#11 20.29 debian/openEMS.packinfo/DESCRIPTION
#11 20.29 debian/openEMS.packinfo/INDEX
#11 20.29 debian/openEMS.packinfo/NEWS
#11 20.29 debian/openems.install
#11 20.29 debian/openems.manpages
#11 20.29 debian/patches/
#11 20.29 debian/patches/0001-Fix-path-to-binaries-for-Debian.patch
#11 20.29 debian/patches/0002-Spelling-fixes.patch
#11 20.29 debian/patches/0003-More-things-to-fix-build.patch
#11 20.29 debian/patches/0004-link-more.patch
#11 20.29 debian/patches/0005-Deletede-CVS-dir-lintian.patch
#11 20.29 debian/patches/0006-Don-t-exit-from-library.patch
#11 20.29 debian/patches/0007-Fix-some-imports-to-make-python-interface-work.patch
#11 20.29 debian/patches/series
#11 20.29 debian/python3-openems.install
#11 20.29 debian/rules
#11 20.29 debian/source/
#11 20.29 debian/source/format
#11 20.29 debian/tests/
#11 20.29 debian/tests/control
#11 20.29 debian/tests/octave-load
#11 20.29 debian/tests/python3-import
#11 20.29 debian/watch
#11 20.38 mk-build-deps: warning:     debian/changelog(l1): version '+git20220725.3d74731-1' is invalid: version number does not start with digit
#11 20.38 LINE: openems (+git20220725.3d74731-1) unstable; urgency=medium
#11 20.62 dh_testdir
#11 20.64 dh_testroot
#11 20.67 dh_prep
#11 20.69 dh_testdir
#11 20.71 dh_testroot
#11 20.74 dh_install
#11 20.78 dh_installdocs
#11 20.82 dh_installchangelogs
#11 20.90 dh_installchangelogs: warning:     debian/changelog(l1): version 'unknown' is invalid: version number does not start with digit
#11 20.90 LINE: openems-build-deps (unknown) unstable; urgency=low
#11 20.90 Can't locate object method "is_valid" via package "unknown" (perhaps you forgot to load "unknown"?) at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 1090.
#11 20.90 make: *** [debian/rules:24: binary-indep] Error 255
#11 20.90 Error in the build process: exit status 2
#11 20.92 dpkg: error: cannot access archive 'openems-build-deps_unknown_all.deb': No such file or directory
#11 20.92 mk-build-deps: dpkg --unpack failed
#11 21.00 debuild: warning:     debian/changelog(l1): version '+git20220725.3d74731-1' is invalid: version number does not start with digit
#11 21.00 LINE: openems (+git20220725.3d74731-1) unstable; urgency=medium
#11 21.05  dpkg-buildpackage -us -uc -ui -b
#11 21.12 dpkg-buildpackage: warning:     debian/changelog(l1): version '+git20220725.3d74731-1' is invalid: version number does not start with digit
#11 21.12 LINE: openems (+git20220725.3d74731-1) unstable; urgency=medium
#11 21.13 dpkg-buildpackage: error: version number does not start with digit
#11 21.13 dpkg-buildpackage: info: source package openems
#11 21.13 dpkg-buildpackage: info: source version unknown
#11 21.13 debuild: fatal error at line 1182:
#11 21.13 dpkg-buildpackage -us -uc -ui -b failed
#11 21.20 Reading package lists...
#11 22.19 Building dependency tree...
#11 22.37 Reading state information...
#11 22.40 E: Unable to locate package openems-build-deps
#11 22.48 Reading package lists...
#11 23.30 E: Unsupported file ./libcsxcad0_*.deb given on commandline
#11 23.30 E: Unsupported file ./libnf2ff0_*.deb given on commandline
#11 23.30 E: Unsupported file ./libopenems0_*.deb given on commandline
#11 23.30 E: Unsupported file ./libqcsxcad0_*.deb given on commandline
#11 23.30 E: Unsupported file ./openems_*.deb given on commandline
#11 23.30 E: Unsupported file ./octave-openems_*.deb given on commandline
#11 23.30 E: Unsupported file ./python3-openems_*.deb given on commandline
------
executor failed running [/bin/sh -c ./build_solver.sh]: exit code: 1
```

**Pull request merged**
